    /* Generated by choco in Thu Jan 24 08:15:39 JST 2008*/
    /* need two nops first */
    nop;
    nop;
    li r1 768;
    slliu r1 r1 4;  /* initialize stack pointer */
    move r62 r1;    /* initialize heap pointer */
    li r61 1023;
    slliu r61 r61 2;
    addiu r60 r61 908;
    calli lib_const_load;
    /* initialize constants */
entry_point1042:
L.1043:
    li r6 0;
    li r6 80;
    put r6;
L.1044:
    halt;
    jumpi L.1044;
    nop;
    /* constants */
    /* Code end */