/* Generated by choco in Mon Jan 21 20:56:47 JST 2008*/
/* need two nops first */
	nop;
	nop;
	li r1 768;
	slliu r1 r1 4;  /* initialize stack pointer */
	move r62 r1;    /* initialize heap pointer */
/* initialize constants */

entry_point1005:
L.1009:
	calli fib_1000;
	li r3 10;
	put r2;
L.1010:
	halt;
	jumpi L.1010;
	nop;
fib_1000:
	subiu r1 r1 2;
L.1011:
	bgei r3 2 L.99;
	li r2 1;
	ret;
	addiu r1 r1 2;
L.99:
	storei r3 r1 0;
	calli fib_1000;
	subiu r3 r3 2;
	storei r2 r1 1;
	loadi r2 r1 0;
	calli fib_1000;
	subiu r3 r2 1;
	loadi r39 r1 1;
	nop;
	adds r2 r2 r39;
	ret;
	addiu r1 r1 2;
/* constants */
/* Code end */
