/* Generated by choco in Mon Jan 21 20:56:48 JST 2008*/
/* need two nops first */
	nop;
	nop;
	li r1 768;
	slliu r1 r1 4;  /* initialize stack pointer */
	move r62 r1;    /* initialize heap pointer */
/* initialize constants */
	loadi r40 r0 L.1011;
	loadi r41 r0 L.1014;
	loadi r42 r0 L.1015;

entry_point1005:
L.1010:
	move r3 r40;
	calli fib_1000;
	nop;
	ftoi r2 r2;
	put r2;
	ret;
	nop;
L.1012:
	halt;
	jumpi L.1012;
	nop;
fib_1000:
	subiu r1 r1 2;
L.1013:
	move r11 r41;
	bgef r3 r11 L.99;
	move r2 r42;
	ret;
	addiu r1 r1 2;
L.99:
	move r9 r41;
	storei r3 r1 0;
	fsub r3 r3 r9;
	calli fib_1000;
	nop;
	move r6 r42;
	storei r2 r1 1;
	loadi r2 r1 0;
	nop;
	fsub r3 r2 r6;
	calli fib_1000;
	nop;
	loadi r39 r1 1;
	nop;
	fadd r2 r2 r39;
	ret;
	addiu r1 r1 2;
/* constants */
L.1011:  .float 3.0;
L.1014:  .float 2.0;
L.1015:  .float 1.0;
/* Code end */
