/* Generated by choco in Wed Jan 23 02:59:04 JST 2008*/
/* need two nops first */
	nop;
	nop;
	li r1 768;
	slliu r1 r1 4;  /* initialize stack pointer */
	move r62 r1;    /* initialize heap pointer */
/* initialize constants */

entry_point1002:
L.1003:
	li r3 40;
	calli create_array;
	li r4 0;
	li r39 30;
	li r3 20;
	li r4 10;
	li r5 0;
	storei r5 r2 0;
	storei r4 r2 1;
	storei r3 r2 2;
	storei r39 r2 3;
	li r39 40;
	li r4 90;
	li r5 80;
	li r6 70;
	li r7 60;
	li r8 50;
	li r9 40;
	li r10 30;
	li r11 20;
	li r12 10;
	li r13 0;
	li r14 90;
	li r15 80;
	li r16 70;
	li r17 60;
	li r18 50;
	li r19 40;
	li r20 30;
	li r21 20;
	li r22 10;
	li r23 0;
	li r24 90;
	li r25 80;
	li r26 70;
	li r27 60;
	li r28 50;
	li r29 40;
	li r30 30;
	li r31 20;
	li r32 10;
	li r33 0;
	li r34 90;
	li r35 80;
	li r36 70;
	li r37 60;
	li r38 50;
	storei r39 r2 4;
	storei r38 r2 5;
	storei r37 r2 6;
	storei r36 r2 7;
	storei r35 r2 8;
	storei r34 r2 9;
	storei r33 r2 10;
	storei r32 r2 11;
	storei r31 r2 12;
	storei r30 r2 13;
	storei r29 r2 14;
	storei r28 r2 15;
	storei r27 r2 16;
	storei r26 r2 17;
	storei r25 r2 18;
	storei r24 r2 19;
	storei r23 r2 20;
	storei r22 r2 21;
	storei r21 r2 22;
	storei r20 r2 23;
	storei r19 r2 24;
	storei r18 r2 25;
	storei r17 r2 26;
	storei r16 r2 27;
	storei r15 r2 28;
	storei r14 r2 29;
	storei r13 r2 30;
	storei r12 r2 31;
	storei r11 r2 32;
	storei r10 r2 33;
	storei r9 r2 34;
	storei r8 r2 35;
	storei r7 r2 36;
	storei r6 r2 37;
	storei r5 r2 38;
	storei r4 r2 39;
	loadi r3 r2 8;
	nop;
	put r3;
L.1004:
	halt;
	jumpi L.1004;
	nop;
/* constants */
/* Code end */
