/* Generated by choco in Mon Jan 21 20:56:47 JST 2008*/
/* need two nops first */
	nop;
	nop;
	li r1 768;
	slliu r1 r1 4;  /* initialize stack pointer */
	move r62 r1;    /* initialize heap pointer */
/* initialize constants */

entry_point1007:
L.1008:
	li r3 a_1000;
	calli fill_1001;
	li r4 0;
	loadi r2 r0 (a_1000 + 9);
	nop;
	put r2;
	ret;
	nop;
L.1009:
	halt;
	jumpi L.1009;
	nop;
fill_1001:
L.1010:
	bli r4 10 L.99;
	ret;
	nop;
L.99:
	adds r2 r3 r4;
	muliu r39 r4 2;
	storei r2 r39 0;
	jumpi L.1010;
	addiu r4 r4 1;
a_1000:
	.int 0;
	.int 0;
	.int 0;
	.int 0;
	.int 0;
	.int 0;
	.int 0;
	.int 0;
	.int 0;
	.int 0;
/* constants */
/* Code end */
