/* Generated by choco in Mon Jan 21 00:53:34 JST 2008*/
/* need two nops first */
	nop;
	nop;
	li r1 768;
	slliu r1 r1 4;  /* initialize stack pointer */
	move r62 r1;    /* initialize heap pointer */
/* initialize constants */
	loadi r41 r0 L.1008;
	loadi r40 r0 L.1007;

entry_point1004:
L.1006:
	loadi r2 r0 x_1000;
	move r8 r40;
	li r7 2;
	move r9 r41;
	nop;
	storei r6 r0 x_1000;
	storei r5 r0 (x_1000 + 1);
	storei r4 r0 (x_1000 + 2);
	storei r3 r0 (x_1000 + 3);
	put r2;
	ret;
	nop;
L.1009:
	halt;
	jumpi L.1009;
	nop;
x_1000:
	.int 1;
	.float 0.0;
	.int 1;
	.int 0;
	.int 1;
	.float 0.0;
	.int 1;
	.int 0;
	.int 1;
	.float 0.0;
	.int 1;
	.int 0;
	.int 1;
	.float 0.0;
	.int 1;
	.int 0;
	.int 1;
	.float 0.0;
	.int 1;
	.int 0;
	.int 1;
	.float 0.0;
	.int 1;
	.int 0;
	.int 1;
	.float 0.0;
	.int 1;
	.int 0;
	.int 1;
	.float 0.0;
	.int 1;
	.int 0;
	.int 1;
	.float 0.0;
	.int 1;
	.int 0;
	.int 1;
	.float 0.0;
	.int 1;
	.int 0;
/* constants */
L.1008:  .int -1;
L.1007:  .float 1.0;
/* Code end */
